# Generated by Django 5.2.2 on 2025-07-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='reason_type',
            field=models.CharField(choices=[('duplicate', 'Potential Duplicate'), ('entry_error', 'Data Entry Error'), ('suspicious', 'Suspicious Entry'), ('inappropriate', 'Inappropriate Content'), ('missing_prerequisite', 'Missing Prerequisite Information'), ('missing_data', 'Missing Data'), ('other', 'Other Reason')], default='other', max_length=32),
        ),
    ]
