# Generated by Django 5.2.2 on 2025-07-27 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0002_favoriteevent_delete_favoritetask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoriteproject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriteproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='favoriteproject',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favoriterespondent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favoriterespondent',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='favoriterespondent',
            name='user',
        ),
        migrations.CreateModel(
            name='FavoriteObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteEvent',
        ),
        migrations.DeleteModel(
            name='FavoriteProject',
        ),
        migrations.DeleteModel(
            name='FavoriteRespondent',
        ),
        migrations.AddIndex(
            model_name='favoriteobject',
            index=models.Index(fields=['user', 'content_type', 'object_id'], name='profiles_fa_user_id_1ec15c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteobject',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
