# Generated by Django 5.2.2 on 2025-06-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('data_collector', 'Data Collector'), ('supervisor', 'Supervisor'), ('meofficer', 'Monitoring and Evaluation Officer'), ('manager', 'Manager'), ('admin', 'Site Administrator')], default='data_collector', help_text='Set user access level and permission. Leave as "Data Collector" if unsure.', max_length=25),
        ),
    ]
