# Generated by Django 5.2.2 on 2025-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('view_only', 'View Only'), ('data_collector', 'Data Collector'), ('supervisor', 'Supervisor'), ('meofficer', 'Monitoring and Evaluation Officer'), ('manager', 'Manager'), ('admin', 'Site Administrator')], default='view_only', help_text='Set user access level and permission. Leave as "Data Collector" if unsure.', max_length=25),
        ),
    ]
