# Generated by Django 5.2.2 on 2025-07-09 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('indicators', '0012_indicatorsubcategory_slug'),
        ('organizations', '0004_organization_full_name'),
        ('projects', '0014_client_full_name_client_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographiccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='demographiccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographiccount',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demographiccount',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.indicatorsubcategory'),
        ),
        migrations.AddField(
            model_name='demographiccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='demographiccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='demographiccount',
            unique_together={('event', 'sex', 'age_range', 'citizenship', 'task', 'subcategory', 'hiv_status', 'pregnancy', 'disability_type', 'kp_type', 'status', 'organization')},
        ),
    ]
