# Generated by Django 5.2.2 on 2025-07-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_demographiccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccount',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18–24'), ('25_34', '25–34'), ('35_44', '35–44'), ('45_64', '45–64'), ('65_plus', '65+')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('non_citizen', 'Non-Citizen')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('VI', 'Visually Impaired'), ('PD', 'Physical Disability'), ('ID', 'Intellectual Disability'), ('HD', 'Hearing Impaired'), ('PSY', 'Psychiatric Disability'), ('SI', 'Speech Impaired'), ('OTHER', 'Other Disability')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='kp_type',
            field=models.CharField(blank=True, choices=[('FSW', 'Female Sex Workers'), ('MSM', 'Men Who Have Sex With Men'), ('PWID', 'People Who Inject Drugs'), ('TG', 'Transgender'), ('INTERSEX', 'Intersex'), ('LBQ', 'Lesbian Bisexual or Queer'), ('OTHER', 'Other Key Population Status')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='status',
            field=models.CharField(blank=True, choices=[('Staff', 'Staff'), ('Community_leader', 'Community Leader'), ('CHW', 'Community Health Worker')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='AgeRange',
        ),
        migrations.DeleteModel(
            name='Citizenship',
        ),
        migrations.DeleteModel(
            name='DisabilityType',
        ),
        migrations.DeleteModel(
            name='KeyPopulationType',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
