# Generated by Django 5.2.2 on 2025-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_demographiccount_age_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographiccount',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
