# Generated by Django 5.2.2 on 2025-07-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_demographiccount_flagged_countflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed'), ('On_Hold', 'On Hold')], default='Planned', max_length=25, verbose_name='Event Status'),
        ),
    ]
