# Generated by Django 5.2.2 on 2025-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccount',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('HIV_Positive', 'HIV Positive'), ('HIV_Negative', 'HIV Negative')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('Pregnant', 'Pregnant'), ('Not_Pregnant', 'Not Pregnant')], max_length=25, null=True),
        ),
    ]
