# Generated by Django 5.2.2 on 2025-07-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_demographiccount_age_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateField(default='2025-07-24'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('hiv_positive', 'HIV Positive'), ('hiv_negative', 'HIV Negative')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('pregnant', 'Pregnant'), ('not_pregnant', 'Not Pregnant')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='demographiccount',
            name='status',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('community_leader', 'Community Leader'), ('CHW', 'Community Health Worker')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('training', 'Training'), ('activity', 'Activity'), ('engagement', 'Engagement'), ('commemoration', 'Commemoration'), ('activation', 'Activation'), ('walkathon', 'Walkathon'), ('counselling_session', 'Counselling Session'), ('other', 'Other')], default='training', max_length=25, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold')], default='planned', max_length=25, verbose_name='Event Status'),
        ),
        migrations.DeleteModel(
            name='CountFlag',
        ),
    ]
