# Generated by Django 5.2.2 on 2025-10-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_event_date_event_start_event_end_and_more'),
        ('organizations', '0006_organization_description'),
        ('projects', '0023_client_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographiccount',
            unique_together={('event', 'sex', 'age_range', 'citizenship', 'task', 'hiv_status', 'pregnancy', 'disability_type', 'kp_type', 'status', 'organization')},
        ),
        migrations.RemoveField(
            model_name='demographiccount',
            name='subcategory',
        ),
    ]
