# Generated by Django 5.2.2 on 2025-10-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_demographiccount_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemographicCount',
        ),
    ]
