# Generated by Django 5.2.2 on 2025-06-11 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='organizations.organization', verbose_name='Project Organized on Behalf of'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ManyToManyField(related_name='partner_organization', through='projects.ProjectOrganization', to='organizations.organization'),
        ),
    ]
