# Generated by Django 5.2.2 on 2025-06-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_indicator_code'),
        ('organizations', '0001_initial'),
        ('projects', '0003_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='indicators',
            field=models.ManyToManyField(blank=True, null=True, through='projects.ProjectIndicator', to='indicators.indicator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='partner_organization', through='projects.ProjectOrganization', to='organizations.organization'),
        ),
    ]
