# Generated by Django 5.2.2 on 2025-06-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_indicator_prerequisite_alter_indicator_created_by_and_more'),
        ('organizations', '0001_initial'),
        ('projects', '0008_task_created_at_task_created_by_task_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='projects.ProjectOrganization', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'organization', 'indicator')},
        ),
    ]
