# Generated by Django 5.2.2 on 2025-06-14 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_target_percentage_of_related_target_related_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_task', to='projects.task'),
        ),
    ]
