# Generated by Django 5.2.2 on 2025-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_remove_indicatorsubcategory_indicator_and_more'),
        ('projects', '0011_alter_target_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='indicators',
            field=models.ManyToManyField(blank=True, through='projects.ProjectIndicator', to='indicators.indicator'),
        ),
    ]
