# Generated by Django 5.2.2 on 2025-07-21 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_parent_organization'),
        ('projects', '0014_client_full_name_client_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectorganization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_links', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectOrganization', through_fields=('project', 'organization'), to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='projectorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_organization', to='organizations.organization'),
        ),
    ]
