# Generated by Django 5.2.2 on 2025-07-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_parent_organization'),
        ('projects', '0015_projectorganization_parent_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='projects.ProjectOrganization', through_fields=('project', 'organization'), to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='projectorganization',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='projects.project'),
        ),
    ]
