# Generated by Django 5.2.2 on 2025-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectactivity_projectactivitycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='cascade_to_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='visible_to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
