# Generated by Django 5.2.2 on 2025-07-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectactivity_cascade_to_children_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectactivity',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='projectactivity',
            old_name='start_date',
            new_name='start',
        ),
    ]
