# Generated by Django 5.2.2 on 2025-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_rename_end_date_projectactivity_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='indicators',
        ),
        migrations.DeleteModel(
            name='ProjectIndicator',
        ),
    ]
