# Generated by Django 5.2.2 on 2025-07-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectdeadlineorganization_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Client Description'),
        ),
    ]
