# Generated by Django 5.2.2 on 2025-10-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0027_delete_indicatorsubcategory'),
        ('organizations', '0006_organization_description'),
        ('projects', '0023_client_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='target',
            name='task',
        ),
        migrations.AddField(
            model_name='target',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.assessment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('project', 'organization', 'indicator', 'assessment')},
        ),
    ]
