# Generated by Django 5.2.2 on 2025-10-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0036_indicator_allow_aggregate_alter_indicator_category_and_more'),
        ('projects', '0024_alter_task_unique_together_remove_target_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_indicator', to='indicators.indicator'),
        ),
    ]
