FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Upgrade pip tools first
RUN pip install --upgrade pip setuptools wheel

RUN pip install -r requirements.txt

COPY . .

# Collect static files (optional for prod)
#RUN python manage.py collectstatic --noinput

CMD ["gunicorn", "bonaso_data_server.wsgi:application", "--bind", "0.0.0.0:8000"]