# Generated by Django 5.2.2 on 2025-06-10 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age_range', models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18_24', '18–24'), ('25_34', '25–34'), ('35_44', '35–44'), ('45_64', '45–64'), ('65_plus', '65+')], max_length=10, null=True, verbose_name='Age Range')),
                ('id_no', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID/Passport Number')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary')], max_length=2, verbose_name='Sex')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ward')),
                ('village', models.CharField(max_length=255, verbose_name='Village')),
                ('district', models.CharField(choices=[('Central', 'Central District'), ('Ghanzi', 'Ghanzi District'), ('Kgalagadi', 'Kgalagadi District'), ('Kgatleng', 'Kgatleng District'), ('Kweneng', 'Kweneng District'), ('North East', 'North East District'), ('North West', 'North West District'), ('South East', 'South East District'), ('Southern', 'Southern District'), ('Chobe', 'Chobe District')], max_length=25, verbose_name='District')),
                ('citizenship', models.CharField(max_length=255, verbose_name='Citizenship/Nationality')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pregnant', models.BooleanField()),
                ('term_began', models.DateField()),
                ('term_ended', models.DateField(blank=True, null=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPopulationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kp_status', models.CharField(blank=True, choices=[('FWS', 'Female Sex Workers'), ('MSM', 'Men Who Have Sex With Men'), ('PWID', 'People Who Inject Drugs'), ('TG', 'Transgender'), ('INTERSEX', 'Intersex'), ('LBQ', 'Lesbian, Bisexual, or Queer'), ('OTHER', 'Other Key Population Status')], max_length=10, null=True, verbose_name='Key Population Status')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='HIVStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv_positive', models.BooleanField()),
                ('date_positive', models.DateField()),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent')),
            ],
        ),
    ]
