# Generated by Django 5.2.2 on 2025-06-11 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicator_created_at_indicator_created_by_and_more'),
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypopulationstatus',
            name='kp_status',
            field=models.CharField(blank=True, choices=[('FSW', 'Female Sex Workers'), ('MSM', 'Men Who Have Sex With Men'), ('PWID', 'People Who Inject Drugs'), ('TG', 'Transgender'), ('INTERSEX', 'Intersex'), ('LBQ', 'Lesbian, Bisexual, or Queer'), ('OTHER', 'Other Key Population Status')], max_length=10, null=True, verbose_name='Key Population Status'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='respondents.respondent')),
            ],
        ),
    ]
