# Generated by Django 5.2.2 on 2025-06-11 23:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_indicator_prerequisite_alter_indicator_created_by_and_more'),
        ('projects', '0007_task'),
        ('respondents', '0002_alter_keypopulationstatus_kp_status_interaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='indicator',
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.indicatorsubcategory'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.task'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
