# Generated by Django 5.2.2 on 2025-06-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0003_remove_interaction_indicator_interaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prerequisite_interaction', to='respondents.interaction'),
        ),
    ]
