# Generated by Django 5.2.2 on 2025-06-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0004_interaction_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypopulationstatus',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kp_status', to='respondents.respondent'),
        ),
    ]
