# Generated by Django 5.2.2 on 2025-06-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_remove_indicatorsubcategory_code'),
        ('respondents', '0005_alter_keypopulationstatus_respondent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='subcategory',
        ),
        migrations.CreateModel(
            name='InteractionSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.interaction')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicatorsubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='subcategories',
            field=models.ManyToManyField(blank=True, null=True, through='respondents.InteractionSubcategory', to='indicators.indicatorsubcategory'),
        ),
    ]
