# Generated by Django 5.2.2 on 2025-06-14 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0006_remove_interaction_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FSW', 'Female Sex Workers'), ('MSM', 'Men Who Have Sex With Men'), ('PWID', 'People Who Inject Drugs'), ('TG', 'Transgender'), ('INTERSEX', 'Intersex'), ('LBQ', 'Lesbian, Bisexual, or Queer'), ('OTHER', 'Other Key Population Status')], max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='keypopulationstatus',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent'),
        ),
        migrations.AddField(
            model_name='keypopulationstatus',
            name='key_population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respondents.keypopulation'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='kp_status',
            field=models.ManyToManyField(blank=True, through='respondents.KeyPopulationStatus', to='respondents.keypopulation'),
        ),
        migrations.AlterUniqueTogether(
            name='keypopulationstatus',
            unique_together={('respondent', 'key_population')},
        ),
        migrations.RemoveField(
            model_name='keypopulationstatus',
            name='kp_status',
        ),
    ]
