# Generated by Django 5.2.2 on 2025-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_remove_indicatorsubcategory_indicator_and_more'),
        ('respondents', '0007_keypopulation_alter_keypopulationstatus_respondent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='subcategories',
            field=models.ManyToManyField(blank=True, through='respondents.InteractionSubcategory', to='indicators.indicatorsubcategory'),
        ),
    ]
