# Generated by Django 5.2.2 on 2025-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0008_alter_interaction_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='numeric_component',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
