# Generated by Django 5.2.2 on 2025-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0009_interaction_numeric_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivstatus',
            name='date_positive',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hivstatus',
            name='hiv_positive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='is_pregnant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='term_began',
            field=models.DateField(blank=True, null=True),
        ),
    ]
