# Generated by Django 5.2.2 on 2025-06-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0010_alter_hivstatus_date_positive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='prerequisite',
        ),
    ]
