# Generated by Django 5.2.2 on 2025-06-17 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0011_remove_interaction_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VI', 'Visually Impaired'), ('PD', 'Physical Disability'), ('ID', 'Intellectual Disability'), ('HD', 'Hearing Impaired'), ('PSY', 'Psychiatric Disability'), ('SI', 'Speech Impaired'), ('OTHER', 'Other Disability')], max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent')),
                ('disability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respondents.disabilitytype')),
            ],
            options={
                'unique_together': {('respondent', 'disability')},
            },
        ),
        migrations.AddField(
            model_name='respondent',
            name='disability_status',
            field=models.ManyToManyField(blank=True, through='respondents.DisabilityStatus', to='respondents.disabilitytype'),
        ),
    ]
