# Generated by Django 5.2.2 on 2025-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0012_disabilitytype_disabilitystatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='disability_status',
            field=models.ManyToManyField(blank=True, through='respondents.DisabilityStatus', to='respondents.disabilitytype', verbose_name='Disability Status'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Is Anonymous'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='kp_status',
            field=models.ManyToManyField(blank=True, through='respondents.KeyPopulationStatus', to='respondents.keypopulation', verbose_name='Key Population Status'),
        ),
    ]
