# Generated by Django 5.2.2 on 2025-06-18 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_updated_by_projectindicator_added_by_and_more'),
        ('respondents', '0013_alter_respondent_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respondent',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='respondent',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
