# Generated by Django 5.2.2 on 2025-06-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0014_interaction_comments_interaction_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
