# Generated by Django 5.2.2 on 2025-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0016_interactionsubcategory_numeric_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='interaction_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Interaction Location'),
        ),
        migrations.AlterField(
            model_name='keypopulation',
            name='name',
            field=models.CharField(choices=[('FSW', 'Female Sex Workers'), ('MSM', 'Men Who Have Sex With Men'), ('PWID', 'People Who Inject Drugs'), ('TG', 'Transgender'), ('INTERSEX', 'Intersex'), ('LBQ', 'Lesbian Bisexual or Queer'), ('OTHER', 'Other Key Population Status')], max_length=10, unique=True),
        ),
    ]
