# Generated by Django 5.2.2 on 2025-07-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0017_interaction_interaction_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondentAttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PLWHIV', 'Person Living with HIV'), ('KP', 'Key Population'), ('Community_Leader', 'Community Leader'), ('CHW', 'Community Health Worker')], max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RespondentAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respondents.respondentattributetype')),
            ],
            options={
                'unique_together': {('respondent', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='respondent',
            name='special_attribute',
            field=models.ManyToManyField(blank=True, through='respondents.RespondentAttribute', to='respondents.respondentattributetype', verbose_name='Special Respondent Attributes'),
        ),
    ]
