# Generated by Django 5.2.2 on 2025-07-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0018_respondentattributetype_respondentattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentattribute',
            name='auto_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='respondentattributetype',
            name='name',
            field=models.CharField(choices=[('PLWHIV', 'Person Living with HIV'), ('PWD', 'Person Living with a Disability'), ('KP', 'Key Population'), ('Community_Leader', 'Community Leader'), ('CHW', 'Community Health Worker')], max_length=25, unique=True),
        ),
    ]
