# Generated by Django 5.2.2 on 2025-07-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0019_respondentattribute_auto_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivstatus',
            name='respondent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent'),
        ),
    ]
