# Generated by Django 5.2.2 on 2025-07-15 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0020_alter_hivstatus_respondent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='auto_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaction',
            name='auto_marked_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interaction',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='flagged_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_flagged_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='marked_ok_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='marked_ok_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_marked_ok_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='marked_ok_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respondentattributetype',
            name='name',
            field=models.CharField(choices=[('PLWHIV', 'Person Living with HIV'), ('PWD', 'Person Living with a Disability'), ('KP', 'Key Population'), ('Community_Leader', 'Community Leader'), ('CHW', 'Community Health Worker'), ('Staff', 'Organization Staff')], max_length=25, unique=True),
        ),
    ]
