# Generated by Django 5.2.2 on 2025-07-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0021_interaction_auto_flag_interaction_auto_marked_ok_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='auto_flag',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='auto_marked_ok',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='flagged_at',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='flagged_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='marked_ok_at',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='marked_ok_by',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='marked_ok_reason',
        ),
        migrations.CreateModel(
            name='InteractionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('auto_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolved_reason', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='respondents.interaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
