# Generated by Django 5.2.2 on 2025-07-15 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0022_remove_interaction_auto_flag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionflag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interactionflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flag_resolved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
