# Generated by Django 5.2.2 on 2025-07-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0024_hivstatus_created_at_hivstatus_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_1', 'Less Than One Year Old'), ('1_4', '1-4'), ('5_9', '5-9'), ('10_14', '10-14'), ('15_19', '15-19'), ('20_24', '20–24'), ('25_29', '25–29'), ('30_34', '30–34'), ('35_39', '35–39'), ('40_44', '40-44'), ('45_49', '45–49'), ('50_54', '50-54'), ('55_55', '55-59'), ('60_64', '60-64'), ('65_plus', '65+')], max_length=10, null=True, verbose_name='Age Range'),
        ),
        migrations.CreateModel(
            name='RespondentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('auto_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolved_reason', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent_flag_created_by', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent_flag_resolved_by', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='respondents.respondent')),
            ],
        ),
    ]
