# Generated by Django 5.2.2 on 2025-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0025_alter_respondent_age_range_respondentflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='dummy_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Estimated DOB from Age Range'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_1', 'Less Than One Year Old'), ('1_4', '1-4'), ('5_9', '5-9'), ('10_14', '10-14'), ('15_19', '15-19'), ('20_24', '20–24'), ('25_29', '25–29'), ('30_34', '30–34'), ('35_39', '35–39'), ('40_44', '40-44'), ('45_49', '45–49'), ('50_54', '50-54'), ('55_59', '55-59'), ('60_64', '60-64'), ('65_plus', '65+')], max_length=10, null=True, verbose_name='Age Range'),
        ),
    ]
