# Generated by Django 5.2.2 on 2025-07-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0026_respondent_dummy_dob_alter_respondent_age_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondentflag',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='respondentflag',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='respondentflag',
            name='respondent',
        ),
        migrations.DeleteModel(
            name='InteractionFlag',
        ),
        migrations.DeleteModel(
            name='RespondentFlag',
        ),
    ]
