# Generated by Django 5.2.2 on 2025-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0027_remove_respondentflag_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='id_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID/Passport Number'),
        ),
    ]
