# Generated by Django 5.2.2 on 2025-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0029_interaction_event_alter_respondentattributetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='plot_no',
            field=models.TextField(blank=True, null=True, verbose_name='Plot Number'),
        ),
    ]
