# Generated by Django 5.2.2 on 2025-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0030_respondent_plot_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='district',
            field=models.CharField(choices=[('Central', 'Central District'), ('Ghanzi', 'Ghanzi District'), ('Kgalagadi', 'Kgalagadi District'), ('Kgatleng', 'Kgatleng District'), ('Kweneng', 'Kweneng District'), ('North East', 'North East District'), ('North West', 'North West District'), ('South East', 'South East District'), ('Southern', 'Southern District'), ('Chobe', 'Chobe District'), ('Gaborone', 'Greater Gaborone Area'), ('Francistown', 'Greater Francistown Area')], max_length=25, verbose_name='District'),
        ),
    ]
