# Generated by Django 5.2.2 on 2025-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0031_alter_respondent_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabilitytype',
            name='name',
            field=models.CharField(choices=[('VI', 'Visually Impaired'), ('PD', 'Physical Disability'), ('ID', 'Intellectual Disability'), ('HI', 'Hearing Impaired'), ('PSY', 'Psychiatric Disability'), ('SI', 'Speech Impaired'), ('OTHER', 'Other Disability')], max_length=10, unique=True),
        ),
    ]
