# Generated by Django 5.2.2 on 2025-10-12 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0026_remove_indicator_subcategories_and_more'),
        ('respondents', '0032_alter_disabilitytype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='event',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='numeric_component',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.CharField(max_length=255)),
                ('response_date', models.DateField(null=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.respondent')),
                ('response_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.option')),
            ],
        ),
        migrations.DeleteModel(
            name='InteractionSubcategory',
        ),
    ]
