# Generated by Django 5.2.2 on 2025-10-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0035_indicator_allow_none'),
        ('respondents', '0033_remove_interaction_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='indicator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='indicators.indicator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='response_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='response_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='respondents.interaction'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.option'),
        ),
        migrations.AlterField(
            model_name='response',
            name='response_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
