# Generated by Django 5.2.2 on 2025-10-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0035_response_comments_response_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respondents.interaction'),
        ),
    ]
