# Generated by Django 5.2.2 on 2025-10-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0036_alter_response_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='response_none',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
