# Generated by Django 5.2.2 on 2025-10-14 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0036_indicator_allow_aggregate_alter_indicator_category_and_more'),
        ('organizations', '0006_organization_description'),
        ('projects', '0024_alter_task_unique_together_remove_target_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_created_by', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AggregateCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('NB', 'Non-Binary')], max_length=2, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('under_1', 'Less Than One Year Old'), ('1_4', '1-4'), ('5_9', '5-9'), ('10_14', '10-14'), ('15_19', '15-19'), ('20_24', '20–24'), ('25_29', '25–29'), ('30_34', '30–34'), ('35_39', '35–39'), ('40_44', '40-44'), ('45_49', '45–49'), ('50_54', '50-54'), ('55_59', '55-59'), ('60_64', '60-64'), ('65_plus', '65+')], max_length=25, null=True)),
                ('district', models.CharField(blank=True, choices=[('Central', 'Central District'), ('Ghanzi', 'Ghanzi District'), ('Kgalagadi', 'Kgalagadi District'), ('Kgatleng', 'Kgatleng District'), ('Kweneng', 'Kweneng District'), ('North East', 'North East District'), ('North West', 'North West District'), ('South East', 'South East District'), ('Southern', 'Southern District'), ('Chobe', 'Chobe District'), ('Gaborone', 'Greater Gaborone Area'), ('Francistown', 'Greater Francistown Area')], max_length=50, null=True)),
                ('citizenship', models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('non_citizen', 'Non-Citizen')], max_length=25, null=True)),
                ('hiv_status', models.CharField(blank=True, choices=[('hiv_positive', 'HIV Positive'), ('hiv_negative', 'HIV Negative')], max_length=25, null=True)),
                ('pregnancy', models.CharField(blank=True, choices=[('pregnant', 'Pregnant'), ('not_pregnant', 'Not Pregnant')], max_length=25, null=True)),
                ('disability_type', models.CharField(blank=True, choices=[('VI', 'Visually Impaired'), ('PD', 'Physical Disability'), ('ID', 'Intellectual Disability'), ('HI', 'Hearing Impaired'), ('PSY', 'Psychiatric Disability'), ('SI', 'Speech Impaired'), ('OTHER', 'Other Disability')], max_length=25, null=True)),
                ('kp_type', models.CharField(blank=True, choices=[('FSW', 'Female Sex Workers'), ('MSM', 'Men Who Have Sex With Men'), ('PWID', 'People Who Inject Drugs'), ('TG', 'Transgender'), ('INTERSEX', 'Intersex'), ('LBQ', 'Lesbian Bisexual or Queer'), ('OTHER', 'Other Key Population Status')], max_length=25, null=True)),
                ('attribute_type', models.CharField(blank=True, choices=[('PLWHIV', 'Person Living with HIV'), ('PWD', 'Person Living with a Disability'), ('KP', 'Key Population'), ('community_leader', 'Community Leader'), ('CHW', 'Community Health Worker'), ('staff', 'Organization Staff')], max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_created_by', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='indicators.option')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_updated_by', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aggregates.aggregategroup')),
            ],
            options={
                'unique_together': {('group', 'sex', 'age_range', 'citizenship', 'hiv_status', 'pregnancy', 'disability_type', 'kp_type', 'attribute_type', 'option')},
            },
        ),
    ]
