# Generated by Django 5.2.2 on 2025-10-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatecount',
            name='unqiue_only',
            field=models.BooleanField(default=False),
        ),
    ]
