# Generated by Django 5.2.2 on 2025-10-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0002_aggregatecount_unqiue_only'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aggregatecount',
            old_name='unqiue_only',
            new_name='unique_only',
        ),
    ]
