# Generated by Django 5.2.2 on 2025-10-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0003_rename_unqiue_only_aggregatecount_unique_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregategroup',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
