# Generated by Django 5.2.2 on 2025-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0004_aggregategroup_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregategroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
