# Generated by Django 5.2.2 on 2025-07-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent_organization',
        ),
    ]
