# Generated by Django 5.2.2 on 2025-06-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='code',
            field=models.TextField(default='TEST101', max_length=10, verbose_name='Indicator Code'),
        ),
    ]
