# Generated by Django 5.2.2 on 2025-06-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicator_created_at_indicator_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Indicator Code'),
        ),
    ]
