# Generated by Django 5.2.2 on 2025-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_alter_indicator_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='status',
            field=models.TextField(choices=[('Active', 'Active'), ('Deprecated', 'Deprecated'), ('Planned', 'Planned')], default='Active', max_length=25, verbose_name='Indicator Status'),
        ),
    ]
