# Generated by Django 5.2.2 on 2025-06-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_indicator_prerequisite_alter_indicator_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsubcategory',
            name='code',
        ),
    ]
