# Generated by Django 5.2.2 on 2025-06-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_remove_indicatorsubcategory_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorsubcategory',
            name='indicator',
        ),
        migrations.AddField(
            model_name='indicator',
            name='subcategories',
            field=models.ManyToManyField(to='indicators.indicatorsubcategory'),
        ),
    ]
