# Generated by Django 5.2.2 on 2025-06-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_remove_indicatorsubcategory_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='require_numeric',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Indicator requires an accompanying numeric value.'),
        ),
    ]
