# Generated by Django 5.2.2 on 2025-06-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_indicator_require_numeric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='indicators.indicatorsubcategory'),
        ),
    ]
