# Generated by Django 5.2.2 on 2025-06-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0011_indicator_updated_by_alter_indicator_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorsubcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
