# Generated by Django 5.2.2 on 2025-07-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0012_indicatorsubcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('Respondent', 'Respondent'), ('Count', 'Count')], default='Respondent', max_length=25, verbose_name='Indicator Type'),
        ),
    ]
