# Generated by Django 5.2.2 on 2025-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0013_indicator_indicator_type'),
        ('respondents', '0018_respondentattributetype_respondentattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='required_attribute',
            field=models.ManyToManyField(blank=True, to='respondents.respondentattributetype'),
        ),
    ]
