# Generated by Django 5.2.2 on 2025-07-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0014_indicator_required_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='allow_repeat',
            field=models.BooleanField(default=False),
        ),
    ]
