# Generated by Django 5.2.2 on 2025-07-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0015_indicator_allow_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='allow_repeat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
