# Generated by Django 5.2.2 on 2025-07-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0018_indicator_match_subcategories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='match_subcategories',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='indicator',
            name='match_subcategories_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_indicators', to='indicators.indicator', verbose_name='Prerequisite Indicators'),
        ),
    ]
