# Generated by Django 5.2.2 on 2025-07-16 12:49

import indicators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0019_remove_indicator_match_subcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='governs_attribute',
            field=models.CharField(blank=True, choices=indicators.models.get_attribute_choices, null=True),
        ),
    ]
