# Generated by Django 5.2.2 on 2025-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0020_indicator_governs_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('Respondent', 'Respondent'), ('Social', 'Social Media Post'), ('Event_No', 'Number of Events'), ('Org_Event_No', 'Number of Organizations at Event'), ('Count', 'Count')], default='Respondent', max_length=25, verbose_name='Indicator Type'),
        ),
    ]
