# Generated by Django 5.2.2 on 2025-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0021_alter_indicator_indicator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('respondent', 'Respondent'), ('social', 'Social Media Post'), ('event_no', 'Number of Events'), ('org_event_no', 'Number of Organizations at Event'), ('count', 'General Count')], default='respondent', max_length=25, verbose_name='Indicator Type'),
        ),
    ]
