# Generated by Django 5.2.2 on 2025-09-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0023_rename_required_attribute_indicator_required_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='indicator_type',
            field=models.CharField(choices=[('respondent', 'Respondent'), ('social', 'Social Media Post'), ('event_no', 'Number of Events'), ('org_event_no', 'Number of Organizations at Event')], default='respondent', max_length=25, verbose_name='Indicator Type'),
        ),
    ]
