# Generated by Django 5.2.2 on 2025-09-19 06:35

import indicators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_alter_indicator_indicator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='governs_attribute',
            field=models.CharField(blank=True, choices=indicators.models.get_attribute_choices, max_length=25, null=True),
        ),
    ]
