# Generated by Django 5.2.2 on 2025-09-19 06:35

import indicators.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0024_alter_indicator_indicator_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='governs_attribute',
            field=models.CharField(blank=True, choices=[
                ('attr1', 'Attribute 1'),
                ('attr2', 'Attribute 2'),
                # Add all your choices here exactly as they were at that time
            ], max_length=25, null=True),
        ),
    ]
