# Generated by Django 5.2.2 on 2025-10-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_demographiccount_unique_together_and_more'),
        ('indicators', '0026_remove_indicator_subcategories_and_more'),
        ('respondents', '0033_remove_interaction_subcategories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorSubcategory',
        ),
    ]
