# Generated by Django 5.2.2 on 2025-10-12 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0027_delete_indicatorsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='code',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='help_text',
        ),
        migrations.AddField(
            model_name='indicator',
            name='match_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indicators.indicator'),
        ),
    ]
