# Generated by Django 5.2.2 on 2025-10-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0028_remove_indicator_code_remove_indicator_help_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='index',
        ),
        migrations.AddField(
            model_name='indicator',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
