# Generated by Django 5.2.2 on 2025-10-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0029_remove_indicator_index_indicator_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logicgroup',
            old_name='operator',
            new_name='group_operator',
        ),
    ]
