# Generated by Django 5.2.2 on 2025-10-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0030_rename_operator_logicgroup_group_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiccondition',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
