# Generated by Django 5.2.2 on 2025-10-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0031_logiccondition_value_boolean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
