# Generated by Django 5.2.2 on 2025-10-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0032_alter_assessment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='logiccondition',
            name='condition_type',
            field=models.CharField(choices=[('any', 'Any'), ('all', 'All'), ('none', 'None')], default='any', max_length=10),
        ),
    ]
