# Generated by Django 5.2.2 on 2025-10-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0033_logiccondition_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccondition',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('all', 'All'), ('none', 'None')], default='any', max_length=10, null=True),
        ),
    ]
