# Generated by Django 5.2.2 on 2025-10-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0034_alter_logiccondition_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='allow_none',
            field=models.BooleanField(default=False),
        ),
    ]
