# Generated by Django 5.2.2 on 2025-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0035_indicator_allow_none'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='allow_aggregate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='category',
            field=models.CharField(choices=[('assessment', 'Assessment-Based'), ('social', 'Social Media'), ('events', 'Number of Events / Outreach'), ('orgs', 'Organizations Capacitated'), ('misc', 'Other Category')], default='assessment', max_length=25),
        ),
        migrations.AlterField(
            model_name='logiccondition',
            name='source_type',
            field=models.CharField(choices=[('assessment', 'Indicator in This Assessment'), ('respondent', 'Respondent Field')], default='assessment', max_length=20),
        ),
    ]
