# Generated by Django 5.2.2 on 2025-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0036_indicator_allow_aggregate_alter_indicator_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccondition',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('any', 'Any'), ('all', 'All'), ('none', 'None')], max_length=10, null=True),
        ),
    ]
