# Generated by Django 5.2.2 on 2025-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0037_alter_logiccondition_condition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiccondition',
            name='operator',
            field=models.CharField(choices=[('=', 'Is Equal To'), ('!=', 'Does Not Equal'), ('>', 'Is Greater Than'), ('<', 'Is Less Than'), ('contains', 'Contains'), ('!contains', 'Does Not Contain')], default='=', max_length=10),
        ),
        migrations.AlterField(
            model_name='logicgroup',
            name='group_operator',
            field=models.CharField(choices=[('AND', 'All Conditions'), ('OR', 'Any Condition')], default='AND', max_length=3),
        ),
    ]
