# Generated by Django 5.2.2 on 2025-10-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0038_alter_logiccondition_operator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='type',
            field=models.CharField(choices=[('boolean', 'Yes/No'), ('single', 'Single Select'), ('multi', 'Mutliselect'), ('text', 'Open Answer'), ('integer', 'Number'), ('multint', 'Numbers by Category')], default='boolean', max_length=25, verbose_name='Data Type'),
        ),
    ]
