from django.utils.timezone import now, localtime
from django.contrib.contenttypes.models import ContentType
from django.apps import apps
from django.db.models import Count, F
from django.db.models.functions import TruncMonth
from django.utils.dateformat import DateFormat

from flags.models import Flag

def create_flag(instance, reason, caused_by, reason_type=Flag.FlagReason.OTHER):
    '''
    Helper function that creates an auto-generated flag.
    - instance (model instnace): instance being flagged
    - reason (string): system generated reason for the flag
    - caused_by (user instance): user whose edit caused the flag, used to determine visibility
    - reason_type (enum): categorical reason for the flag
    '''

    flag = Flag.objects.create(
        content_type=ContentType.objects.get_for_model(instance),
        object_id = instance.id,
        reason_type=reason_type,
        reason=reason,
        auto_flagged=True,
        caused_by=caused_by
    )
    print('user', flag.caused_by.username)
def resolve_flag(flags_qs, reason):
    '''
    Helper function that automatically resolves flags if the issue is fixed (for system generated).
    - flag_qs (queryset): queryset of related flags
    - reason (string): reason to resolve
    '''
    to_resolve = flags_qs.filter(reason=reason, auto_flagged=True, resolved=False).first()
    if to_resolve:
        to_resolve.resolved = True
        to_resolve.auto_resolved = True
        to_resolve.resolved_at = now()
        to_resolve.save()

def get_object_from_str(model_str: str, object_id: int):
    '''
    Get the object from a model string/id
    - model_str (string): app/modle name of the object in the appname.modelname format
    - object_id (integer): the id of the object
    '''
    try:
        app_label, model_name = model_str.lower().split('.')
        model = apps.get_model(app_label, model_name)
        if not model:
            return None
        return model.objects.get(pk=object_id)
    except (ValueError, LookupError, model.DoesNotExist):
        return None

def get_flag_metadata(queryset):
    '''
    Given a queryset of flags, returns summary statistics
    '''
    total = queryset.count() #number of flags
    auto_flagged = queryset.filter(auto_flagged=True).count() #autogenerated
    active = queryset.filter(resolved=False).count() #active/unresolved
    by_type = queryset.values("reason_type").annotate(count=Count("id")) #breakdown by reason type
    by_model = (
        queryset
        .values(
            app_label=F("content_type__app_label"),
            model=F("content_type__model")
        )
        .annotate(count=Count("id"))
    ) #by related model

    by_month = queryset.annotate(
        month=TruncMonth('created_at')
    ).values('month').annotate(
        count=Count('id')
    ).order_by('month') #by month
        
    return {
        'total': total,
        'auto_flagged': auto_flagged,
        'active': active,
        'by_type': by_type,
        'by_model': by_model,
        'by_month': by_month,
    }
