# Generated by Django 5.2.2 on 2025-07-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_send_to_admin_alter_messagerecipient_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
    ]
