# Generated by Django 5.2.2 on 2025-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_edited_on_alter_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
