# Generated by Django 5.2.2 on 2025-07-17 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0020_indicator_governs_attribute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy')], max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_filter', to='analysis.chartfield')),
            ],
        ),
        migrations.CreateModel(
            name='ChartParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_param', to='analysis.chartfield')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_filter', to='analysis.chartfield')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL)),
                ('filters', models.ManyToManyField(blank=True, through='analysis.DashboardFilter', to='analysis.chartfield')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardIndicatorChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.dashboardsetting')),
            ],
        ),
        migrations.AddField(
            model_name='dashboardfilter',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.dashboardsetting'),
        ),
        migrations.CreateModel(
            name='IndicatorChartSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(blank=True, choices=[('Pie', 'Pie Chart'), ('Line', 'Line Chart'), ('Bar', 'Bar')], default='Bar', max_length=25, null=True)),
                ('tabular', models.BooleanField(default=False)),
                ('split', models.CharField(blank=True, choices=[('Month', 'Month'), ('Quarter', 'Quarter')], default='Quarter', max_length=25, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_settings_created_by', to=settings.AUTH_USER_MODEL)),
                ('filters', models.ManyToManyField(blank=True, related_name='chart_filters', through='analysis.ChartFilter', to='analysis.chartfield')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
                ('params', models.ManyToManyField(blank=True, related_name='chart_params', through='analysis.ChartParam', to='analysis.chartfield')),
            ],
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='charts',
            field=models.ManyToManyField(blank=True, through='analysis.DashboardIndicatorChart', to='analysis.indicatorchartsetting'),
        ),
        migrations.AddField(
            model_name='dashboardindicatorchart',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.indicatorchartsetting'),
        ),
        migrations.AddField(
            model_name='chartparam',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_for_param', to='analysis.indicatorchartsetting'),
        ),
        migrations.AddField(
            model_name='chartfilter',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_for_filter', to='analysis.indicatorchartsetting'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardfilter',
            unique_together={('dashboard', 'field', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='dashboardindicatorchart',
            unique_together={('dashboard', 'chart')},
        ),
        migrations.AlterUniqueTogether(
            name='chartparam',
            unique_together={('chart', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='chartfilter',
            unique_together={('chart', 'field', 'value')},
        ),
    ]
