# Generated by Django 5.2.2 on 2025-07-18 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('projects', '0014_client_full_name_client_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='chartfield',
            name='name',
            field=models.CharField(choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('subcategory', 'Indicator Subcategory')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('Pie', 'Pie Chart'), ('Line', 'Line Chart'), ('Bar', 'Bar Chart')], default='Bar', max_length=25, null=True),
        ),
    ]
