# Generated by Django 5.2.2 on 2025-07-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_dashboardsetting_project_alter_chartfield_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardsetting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
