# Generated by Django 5.2.2 on 2025-07-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_dashboardsetting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorchartsetting',
            name='params',
        ),
        migrations.RenameField(
            model_name='indicatorchartsetting',
            old_name='split',
            new_name='period',
        ),
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='legend',
            field=models.CharField(blank=True, choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('subcategory', 'Indicator Subcategory')], default=None, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='ChartParam',
        ),
    ]
