# Generated by Django 5.2.2 on 2025-07-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_remove_indicatorchartsetting_params_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorchartsetting',
            old_name='period',
            new_name='axis',
        ),
    ]
