# Generated by Django 5.2.2 on 2025-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_rename_period_indicatorchartsetting_axis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='axis',
            field=models.CharField(blank=True, choices=[('month', 'Month'), ('quarter', 'Quarter')], default='quarter', max_length=25, null=True),
        ),
    ]
