# Generated by Django 5.2.2 on 2025-07-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_indicatorchartsetting_axis'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='use_target',
            field=models.BooleanField(default=False),
        ),
    ]
