# Generated by Django 5.2.2 on 2025-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_indicatorchartsetting_use_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='stack',
            field=models.CharField(blank=True, choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('subcategory', 'Indicator Subcategory')], default=None, max_length=25, null=True),
        ),
    ]
