# Generated by Django 5.2.2 on 2025-07-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_indicatorchartsetting_stack'),
        ('indicators', '0023_rename_required_attribute_indicator_required_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartfield',
            name='name',
            field=models.CharField(choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('organization', 'Organization'), ('subcategory', 'Indicator Subcategory')], max_length=25, unique=True),
        ),
        migrations.RemoveField(
            model_name='indicatorchartsetting',
            name='indicator',
        ),
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='legend',
            field=models.CharField(blank=True, choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('organization', 'Organization'), ('subcategory', 'Indicator Subcategory')], default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='stack',
            field=models.CharField(blank=True, choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('organization', 'Organization'), ('subcategory', 'Indicator Subcategory')], default=None, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='ChartIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.indicatorchartsetting')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicators.indicator')),
            ],
            options={
                'unique_together': {('chart', 'indicator')},
            },
        ),
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='indicator',
            field=models.ManyToManyField(through='analysis.ChartIndicator', to='indicators.indicator'),
        ),
    ]
