# Generated by Django 5.2.2 on 2025-08-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_alter_chartfield_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorchartsetting',
            old_name='indicator',
            new_name='indicators',
        ),
    ]
