# Generated by Django 5.2.2 on 2025-08-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_rename_indicator_indicatorchartsetting_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='chart_type',
            field=models.CharField(blank=True, choices=[('pie', 'Pie Chart'), ('line', 'Line Chart'), ('bar', 'Bar Chart')], default='bar', max_length=25, null=True),
        ),
    ]
