# Generated by Django 5.2.2 on 2025-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_alter_chartfield_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='repeat_n',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='repeat_only',
            field=models.BooleanField(default=False),
        ),
    ]
