# Generated by Django 5.2.2 on 2025-08-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_indicatorchartsetting_repeat_n_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicatorchartsetting',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='indicatorchartsetting',
            old_name='start_date',
            new_name='start',
        ),
    ]
