# Generated by Django 5.2.2 on 2025-08-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_rename_end_date_indicatorchartsetting_end_and_more'),
        ('organizations', '0006_organization_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsetting',
            name='cascade_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dashboardsetting',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
