# Generated by Django 5.2.2 on 2025-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_dashboardsetting_cascade_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
