# Generated by Django 5.2.2 on 2025-10-18 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0020_alter_chartfield_name_and_more'),
        ('indicators', '0038_alter_logiccondition_operator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linelist',
            name='indicator',
        ),
        migrations.AddField(
            model_name='linelist',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicators.assessment'),
        ),
    ]
