# Generated by Django 5.2.2 on 2025-10-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_remove_linelist_indicator_linelist_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartfield',
            name='name',
            field=models.CharField(choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('special_attribute', 'Special Respondent Attribute'), ('district', 'District'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('organization', 'Organization'), ('option', 'Option'), ('platform', 'Platform'), ('metric', 'Metric')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='legend',
            field=models.CharField(blank=True, choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('special_attribute', 'Special Respondent Attribute'), ('district', 'District'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('organization', 'Organization'), ('option', 'Option'), ('platform', 'Platform'), ('metric', 'Metric')], default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='indicatorchartsetting',
            name='stack',
            field=models.CharField(blank=True, choices=[('age_range', 'Age Range'), ('sex', 'Sex'), ('kp_type', 'Key Population Type'), ('disability_type', 'Disability Type'), ('special_attribute', 'Special Respondent Attribute'), ('district', 'District'), ('citizenship', 'Citizenship'), ('hiv_status', 'HIV Status'), ('pregnancy', 'Pregnancy'), ('organization', 'Organization'), ('option', 'Option'), ('platform', 'Platform'), ('metric', 'Metric')], default=None, max_length=25, null=True),
        ),
    ]
