# Generated by Django 5.2.2 on 2025-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_alter_chartfield_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorchartsetting',
            name='average',
            field=models.BooleanField(default=False),
        ),
    ]
