# Generated by Django 5.2.2 on 2025-07-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectdeadline_projectdeadlineorganization_and_more'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediapost',
            name='task',
        ),
        migrations.CreateModel(
            name='SocialMediaPostTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialmediapost')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.task')),
            ],
        ),
        migrations.AddField(
            model_name='socialmediapost',
            name='tasks',
            field=models.ManyToManyField(blank=True, through='social.SocialMediaPostTasks', to='projects.task'),
        ),
    ]
