# Generated by Django 5.2.2 on 2025-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_socialmediapost_task_socialmediaposttasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediapost',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
