# Generated by Django 5.2.2 on 2025-07-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_socialmediapost_published_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaPostFlag',
        ),
    ]
