# Generated by Django 5.2.2 on 2025-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_delete_socialmediapostflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='reach',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
