# Generated by Django 5.2.2 on 2025-10-24 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_description'),
        ('social', '0005_socialmediapost_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediapost',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
